name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Install dependencies
        run: just install

      - name: Run linters
        run: just lint

      - name: Run tests
        run: just test

      - name: Build
        run: just build
